### ISSUE TITLE
GetActiveItems does not return the correct list if no active items

### ISSUE THREAD

**Issue by jsandv** [technosoftware-gmbh/opc-daae-server-sdk#1]
In the RefreshThread of ClassicNodeManager.cs (https://github.com/technosoftware-gmbh/opc-daae-server-sdk/blob/master/examples/net/C%23/DaSampleServer/ClassicNodeManager.cs)

I Included the sample code  
```
// Sample how to get a list of active items (used at least by one client)
int numHandles;
IntPtr[] itemHandles;
GetActiveItems(out numHandles, out itemHandles);
```
I am experiencing one critical issue where the method GetActiveItems does not return the correct list of items. This happens when there is no active subscription or if theres isnt any items active. GetActiveItems will return the "last list of active handles". Not empty list.

Steps to reproduce				
1. if one client with one subscription is connected to server, then its not possible to deactivate the subscription from client side. If the subscription is active; then you cannot deactivate all the items individually from client side either. Last state where there where active items is continously returned
2. while two or more clients then problem mentioned above dissappears. (untill the other clients disconnects)

**Comment by technosoftware** [comment]
- For the .NET version parameter numItemHandles now returns 0 and deviceItemHandles returns an empty list.
- The C++ version was already correct but the Log entry was wrong
